import {
  Body,
  Controller,
  Get,
  HttpCode,
  HttpStatus,
  Param,
  Post,
  Query,
} from '@nestjs/common';
import {
  AgentPatch,
  AgentRun,
  ApplyPatchRequest,
  CreatePullRequestFromAgentRequest,
  DispatchAgentRequest,
  DispatchAgentResponse,
} from '@devflow/shared-types';
import { AgentOrchestratorService } from './agent-orchestrator.service';
import { ToolRegistryService, ToolDefinition } from './tools/tool-registry.service';

@Controller('api/v1/workspaces/:workspaceId/repositories/:repositoryId/agents')
export class AgentsController {
  constructor(
    private readonly orchestrator: AgentOrchestratorService,
    private readonly toolRegistry: ToolRegistryService,
  ) {}

  /**
   * Get all registered controlled tools
   */
  @Get('tools')
  getTools(): ToolDefinition[] {
    return this.toolRegistry.getToolDefinitions();
  }

  /**
   * Dispatch an Autonomous AI Agent Run
   */
  @Post('dispatch')
  @HttpCode(HttpStatus.OK)
  async dispatchAgent(
    @Param('workspaceId') workspaceId: string,
    @Param('repositoryId') repositoryId: string,
    @Body() body: DispatchAgentRequest,
  ): Promise<DispatchAgentResponse> {
    const request: DispatchAgentRequest = {
      ...body,
      workspaceId: workspaceId || body.workspaceId,
      repositoryId: repositoryId || body.repositoryId,
    };
    const run = await this.orchestrator.dispatchAgent(request);
    return { run };
  }

  /**
   * List all agent runs for workspace and repository
   */
  @Get('runs')
  listRuns(
    @Param('workspaceId') workspaceId: string,
    @Param('repositoryId') repositoryId: string,
  ): AgentRun[] {
    return this.orchestrator.listRuns(workspaceId, repositoryId);
  }

  /**
   * Get specific agent run by ID
   */
  @Get('runs/:runId')
  getRun(@Param('runId') runId: string): AgentRun {
    return this.orchestrator.getRun(runId);
  }

  /**
   * Cancel an active agent run
   */
  @Post('runs/:runId/cancel')
  @HttpCode(HttpStatus.OK)
  cancelRun(@Param('runId') runId: string): AgentRun {
    return this.orchestrator.cancelRun(runId);
  }

  /**
   * Apply a code patch generated by an agent run
   */
  @Post('runs/:runId/apply-patch')
  @HttpCode(HttpStatus.OK)
  applyPatch(
    @Param('runId') runId: string,
    @Body() body: ApplyPatchRequest,
  ): AgentPatch {
    return this.orchestrator.applyPatch(runId, body.patchId);
  }

  /**
   * Create a GitHub Pull Request from an agent run
   */
  @Post('runs/:runId/create-pr')
  @HttpCode(HttpStatus.OK)
  createPullRequest(
    @Param('runId') runId: string,
    @Body() body: CreatePullRequestFromAgentRequest,
  ): { prNumber: number; prUrl: string } {
    return this.orchestrator.createPullRequestFromRun(
      runId,
      body.title,
      body.body,
      body.baseBranch,
    );
  }
}
